export { default as baner1 } from './port1.jpg'
export { default as baner2 } from './bandSite.jpg'
export { default as baner3 } from './chuva.jpg'
export { default as baner4 } from './NFLX.jpg'
export { default as baner5 } from './port2.jpg'
export { default as baner6 } from './tipogeo.jpg'
export { default as baner7 } from './typing.jpg'
export { default as baner8 } from './letmeask.jpg'
